/**
 * Karty Łąki (GDD v0.3, sekcje 7.2, 8, 7.6, 13.5). Karty dają: talia startowa, stworki (przy złapaniu
 * i awansie na poziom 2) oraz brainglamy (kopia przy każdej przemianie). Nazwy i opisy w jednym miejscu.
 * `power` = siła przy poprawnej odpowiedzi; `power2` = liczba ciosów (multiHit) albo tarcza (combo).
 */
import type { CardDef, CardGrants } from '../core/types';

export const CARDS: Record<string, CardDef> = {
  'cios-plusika': {
    id: 'cios-plusika',
    name: 'Cios Plusika',
    // Karta startowa i karta Plusika — sourceId pozwala wzmocnić ją na poziomie 3 Plusika.
    source: 'starter',
    sourceId: 'plusik',
    rarity: 'common',
    kind: 'attack',
    cost: 1,
    power: 8,
    power2: 0,
    pool: 'attack',
    description: 'Zdejmij 8 Czaru.',
    art: 'creature:plusik',
  },
  'tarcza-z-lisci': {
    id: 'tarcza-z-lisci',
    name: 'Tarcza z liści',
    source: 'starter',
    sourceId: null,
    rarity: 'common',
    kind: 'shield',
    cost: 1,
    power: 8,
    power2: 0,
    pool: 'defend',
    description: 'Tarcza: 8.',
    art: 'creature:plusik',
  },
  'tarcza-dopelniaka': {
    id: 'tarcza-dopelniaka',
    name: 'Tarcza Dopełniaka',
    source: 'creature',
    sourceId: 'dopelniak',
    rarity: 'common',
    kind: 'shield',
    cost: 1,
    power: 12,
    power2: 0,
    pool: 'defend',
    description: 'Tarcza: 12.',
    art: 'creature:dopelniak',
  },
  'podwojny-dziob': {
    id: 'podwojny-dziob',
    name: 'Podwójny dziób',
    source: 'creature',
    sourceId: 'blizniak',
    rarity: 'uncommon',
    kind: 'strongAttack',
    cost: 2,
    power: 20,
    power2: 0,
    pool: 'strongAttack',
    description: 'Zdejmij 20 Czaru.',
    art: 'creature:blizniak',
  },
  'koniczynowa-tarcza': {
    id: 'koniczynowa-tarcza',
    name: 'Koniczynowa tarcza',
    source: 'creature',
    sourceId: 'koniczynek',
    rarity: 'rare',
    kind: 'bigShield',
    cost: 1,
    power: 22,
    power2: 0,
    pool: 'strongDefend',
    description: 'Wielka tarcza: 22.',
    art: 'creature:koniczynek',
  },
  'lepka-kokarda': {
    id: 'lepka-kokarda',
    name: 'Lepka kokarda',
    source: 'glam',
    sourceId: 'slimakorro',
    rarity: 'uncommon',
    kind: 'weaken',
    cost: 1,
    // Procent osłabienia następnego ruchu brainrota.
    power: 50,
    power2: 0,
    pool: 'defend',
    description: 'Następny ruch brainrota słabszy o połowę.',
    art: 'glam:slimakorro',
  },
  'brokatowy-roj': {
    id: 'brokatowy-roj',
    name: 'Brokatowy rój',
    source: 'glam',
    sourceId: 'trzmielini',
    rarity: 'uncommon',
    kind: 'multiHit',
    cost: 1,
    power: 4,
    power2: 3,
    pool: 'attack',
    description: '3 ciosy po 4 Czaru.',
    art: 'glam:trzmielini',
  },
  'perlowy-zdroj': {
    id: 'perlowy-zdroj',
    name: 'Perłowy zdrój',
    source: 'glam',
    sourceId: 'grzybello',
    rarity: 'uncommon',
    kind: 'heal',
    cost: 1,
    power: 15,
    power2: 0,
    pool: 'defend',
    description: 'Ulecz 15 serduszek.',
    art: 'glam:grzybello',
  },
  'krolewski-bukiet': {
    id: 'krolewski-bukiet',
    name: 'Królewski bukiet',
    source: 'glam',
    sourceId: 'kosiarrini',
    rarity: 'legendary',
    kind: 'combo',
    cost: 2,
    power: 14,
    power2: 10,
    pool: 'strongAttack',
    description: '14 Czaru i tarcza 10.',
    art: 'glam:kosiarrini',
  },
};

/** Skąd dziecko dostaje karty (GDD 13.5): talia startowa, stworki, brainglamy. */
export const CARD_GRANTS: CardGrants = {
  starter: { 'cios-plusika': 5, 'tarcza-z-lisci': 3 },
  creatures: {
    plusik: { cardId: 'cios-plusika', onCatch: 1, onLevelUp: 1 },
    dopelniak: { cardId: 'tarcza-dopelniaka', onCatch: 2, onLevelUp: 1 },
    blizniak: { cardId: 'podwojny-dziob', onCatch: 2, onLevelUp: 1 },
    koniczynek: { cardId: 'koniczynowa-tarcza', onCatch: 1, onLevelUp: 1 },
  },
  glams: {
    slimakorro: 'lepka-kokarda',
    trzmielini: 'brokatowy-roj',
    grzybello: 'perlowy-zdroj',
    kosiarrini: 'krolewski-bukiet',
  },
};
